# fly.toml file generated for winter-feather-8061 on 2022-11-10T10:00:25+07:00

app = "{{cookiecutter.project_slug}}"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DB_FILE = "/mnt/data/db.sqlite3"
  DB_FILE_QUEUE = "/mnt/data/db-huey.sqlite3"
  DJANGO_ADMIN_URL = "admin/"
  DJANGO_DEFAULT_FROM_EMAIL = "{{cookiecutter.email}}"
  DJANGO_SETTINGS_MODULE = "config.settings.production"
  REPLICA_URL = "s3://{{cookiecutter.project_slug}}/db.sqlite3"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/mnt/data"
  source = "data"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 40
    soft_limit = 35
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/ht/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
      Host = "health.check"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
