name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
          cache: pip
          cache-dependency-path: |
            {{cookiecutter.project_slug}}/requirements/base.txt
            {{cookiecutter.project_slug}}/requirements/local.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cookiecutter, lint & test
        run: |
          cookiecutter . --no-input --overwrite-if-exists "$@"
          cd my_awesome_project
          pip install -r requirements/local.txt
          git init
          git add .
          make check
          make coverage
